services:
  sqlserver:
    image: sql_server_image
    container_name: image-grouping-sqlserver
    environment:
      SA_PASSWORD: "${SA_PASSWORD:-abc1234}"
      ACCEPT_EULA: "Y"
    volumes:
      - kyc-saga-sqldb:/var/opt/mssql
    restart: unless-stopped
    networks:
      - app-network
    ports:
      - '127.0.0.1:1433:1433'
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -U sa -P $${MSSQL_SA_PASSWORD} -Q 'SELECT 1'"]
      interval: 5s
      timeout: 5s
      retries: 10

  image_grouping:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: image-grouping-service
    depends_on:
      - sqlserver      
    volumes:
      - ./logs:/app/logs
      - ./Thumbnails:/app/image_face_detection/Thumbnails
      - ./individuals_portraits:/app/individuals_portraits:rw
      - image_grouping_uploaded:/app/image_face_detection/Images:ro
      - "./cache/deepface:/root/.deepface:rw"
    env_file:
      - docker/.env.example
      - ./.env
    environment:
      USE_SQL_AUTH: "${USE_SQL_AUTH:-true}"
      SQL_SERVER: "${SQL_SERVER:-123.123.1.123}"
      SQL_DATABASE: "${SQL_DATABASE:-database}"
      SQL_USER: "${SQL_USER:-admin}"
      SQL_PASSWORD: "${SQL_PASSWORD:-abc1234}"
      DEEPFACE_HOME: /root/.deepface

      # >>> Recluster mode (single pass) <<<
      SERVICE: recognition
      MODE: once
      RECOGNIZER_ARGS: "--recluster"

      # If you prefer the app's internal 3-min loop, use:
      # MODE: once
      # RECOGNIZER_ARGS: "--automate"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "python ./docker/healthcheck.py"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    entrypoint: ["docker-entrypoint.sh"]

volumes:
  kyc-saga-sqldb:
  image_grouping_uploaded:
    driver: local
    driver_opts:
      type: cifs
      o:  username=administrator,password=abc1234
      device: "//123.123.1.123/files/Uploaded"

networks:
  app-network:

    driver: bridge  
