services:
  sqlserver:
    image: sql_server_image
    container_name: image-grouping-sqlserver
    environment:
      SA_PASSWORD: "${SA_PASSWORD:-pass1234}"
      ACCEPT_EULA: "Y"
    volumes:
      - kyc-saga-sqldb:/var/opt/mssql
    restart: unless-stopped
    networks:
      - app-network
    ports:
      - '127.0.0.1:1433:1433'
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -U sa -P $${MSSQL_SA_PASSWORD} -Q 'SELECT 1'"]
      interval: 5s
      timeout: 5s
      retries: 10

  image_grouping:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: image-grouping-service
    depends_on:
      - sqlserver      
    volumes:
      - ./person_recognition/logs:/app/services/image_grouping/person_recognition/logs
      - ./image_face_detection/logs:/app/services/image_grouping/image_face_detection/logs
      - ./Thumbnails:/app/services/image_grouping/image_face_detection/Thumbnails
      - ./individuals_portraits:/app/services/image_grouping/individuals_portraits:rw
      - image_grouping_uploaded:/app/services/image_grouping/image_face_detection/Images:ro
      - "C:/Users/user1/Desktop/Deep-Frame/services/image_grouping/Thumbnails:/app/services/image_grouping/image_face_detection/Thumbnails:rw"
      - "./cache/deepface:/root/.deepface:rw"
    env_file:
      - docker/.env.example
      - ./.env
    environment:
      USE_SQL_AUTH: "${USE_SQL_AUTH:-true}"
      SQL_SERVER: "${SQL_SERVER:-123.123.1.123}"
      SQL_DATABASE: "${SQL_DATABASE:-database}"
      SQL_USER: "${SQL_USER:-user}"
      SQL_PASSWORD: "${SQL_PASSWORD:-pass1234}"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "python ./docker/healthcheck.py"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    entrypoint: ["docker-entrypoint.sh"]

volumes:
  kyc-saga-sqldb:
  image_grouping_uploaded:
    driver: local
    driver_opts:
      type: cifs
      o:  username=administrator,password=pass1234
      device: "//123.123.1.123/files/location"

networks:
  app-network:
    driver: bridge  

